version: '3.1'
services:
  flask:
    build: .
    image: matthesrieke/timo-evaluation:1.1.0
    environment:
      - SERVICE_URL=http://localhost:8080
    volumes:
      - ./server:/app
    ports:
      - 8080:80
